### ISSUE TITLE
Popup giving a 404

### ISSUE THREAD

**Issue by soccernicolas** [geofs-plugins/voice-atc#4]
The plugin still works, it pops up in the geofs window asking you to enter a frequency.
But once you enter the frequency, the popup that would start the actual session returns a 404.

**Comment by yotam180** [comment]
The server's probably down. I doubt it works anymore...

**Comment by sushrey** [comment]
> The server's probably down. I doubt it works anymore...

what!! how can you say that? i hv been trying soo hard to get it right . now can you  please tell me if there is any way to fix it?

**Comment by yotam180** [comment]
I really afraid the problem is on our side here... Since Google took down our extension ~two years ago, we never had enough interest to bring it back up. Sorry bud 😞

**Comment by sushrey** [comment]
It's ok I guess nothing much can be done about it. But by the way I had to
tell that there are aircraft missing you in geofs with me. A320
(airberlin), 757 (delta) a330(Singapore and Air Asia) and some others are
missing. Can you help?

**Comment by yotam180** [comment]
Maybe Harry Xue can help you. I don't remember exactly but I think he was one of the people who developed them. Those are not mine. 🤷

**Comment by sushrey** [comment]
It's OK all right? 😊 You don't have to get soo serious.

**Comment by yotam180** [comment]
Sure thing...
